---
- name: builder env server
  hosts: builderhosts
  become: yes

  roles: 
   - dockerenvo
   - dockerhubconn
   - docker_works

- name: runner env server
  hosts: prodhosts
  become: yes

  roles:
   - dockerenvo
   - dockerhubconn
   - docker_host