---
- name: builder env server
  hosts: web
  become: yes

  roles: 
   - dockerenvo
   - dockerhubconn
   - docker_works

- name: runner env server
  hosts: builder
  become: yes

  roles:
   - dockerenvo
   - dockerhubconn
   - docker_host