---
- name: builder env server
  hosts: builderhost
  become: yes

  roles: 
   - dockerenvo
   - dockerhubconn
   - docker_works

- name: runner env server
  hosts: prodhost
  become: yes

  roles:
   - dockerenvo
   - dockerhubconn
   - docker_host