project_name         = "formal-branch-298717"
gcp_credentials_path = "/home/newshoosha/gkey.json"
region               = "europe-north1"
zone                 = "europe-north1-a"
ssh_username         = "ubuntu"
ssh_pub_key_path     = "~/.ssh/gkey"