project_name         = "My First Project"
gcp_credentials_path = "/home/newshoosha/gkey.json"
region               = "a"
zone                 = "europe-north1"
ssh_username         = "ubuntu"
ssh_pub_key_path     = "~/.ssh/gkey"