---
# tasks file for dockerenvo
- name: Ensure that DOCKER daemon and Python env is present
  apt:
    pkg:
      - docker.io
      - python-pip
      - python-docker
      - python3
      - python3-pip
    state: present
    update_cache: yes

- name: Ensure module docker-py is present
  pip:
    name: docker-py
    state: present