---
# tasks file for docker_works
- name: Copy my dockerfile
  copy:
    src: Dockerfile
    dest: '{{ dest_dockerfile }}/Dockerfile'

- name: Ensure image is build and pushed from Builderhost to DH
  docker_image:
    name: '{{ my_boxfuse }}'
    path: '{{ dest_dockerfile }}/'
    state: present
    push: yes
    